services:
  - type: web
    name: crud-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn crud.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
